-- GOLD CONSUMPTION and backflush based on BOM calculation 
WITH bom_rate AS (
    SELECT
        MATERIAL_NUMBER,
        BILL_OF_MATERIAL_NUMBER,
        ALTERNATIVE_BOM,
        PLANT,
        BOM_COMPONENT,
        ALTERNATIVE_BOM_DESCRIPTION,
        COMPONENT_QUANTITY,
        BASE_QUANTITY,
        COMPONENT_UNIT_OF_MEASURE AS GOLD_UNIT
    FROM MLX_HARMONIZED.MLX_MASTER.BASIC_MANUFACTURING_BOM
    WHERE PLANT = '1901'
        AND BOM_COMPONENT IN (
            '000000000080950001',
            '000000008000063922',
            '000000000080950004'
        )
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY MATERIAL_NUMBER, BILL_OF_MATERIAL_NUMBER,
                        ALTERNATIVE_BOM, PLANT, BOM_COMPONENT
        ORDER BY VALID_FROM_DATE DESC, HEADER_COUNTER DESC,
                    ITEM_COUNTER DESC, ITEM_SELECTION_COUNTER DESC
    ) = 1
),
daily_yield AS (
    SELECT
        AUFNR,
        TO_DATE(BUDAT, 'YYYYMMDD') AS POSTING_DATE,
        SUM(GMNGA) AS DAY_YIELD,
        SUM(XMNGA) AS DAY_SCRAP,
        GMEIN AS YIELD_UNIT
    FROM MLX_DATALAKE.MLX_SAP_ECC.AFRU
    WHERE WERKS = '1901'
        AND VORNR = '0020'
    GROUP BY AUFNR, BUDAT, GMEIN
)
SELECT
    d.AUFNR AS ORDER_NUMBER,
    r.BAUGR AS PARENT_MATERIAL,
    r.MATNR AS GOLD_CODE,
    r.STLNR AS BOM_NUMBER,
    r.STLAL AS ALTERNATIVE_BOM,
    b.ALTERNATIVE_BOM_DESCRIPTION AS LOCATION,
    d.POSTING_DATE,
    d.DAY_YIELD,
    b.COMPONENT_QUANTITY AS BOM_GOLD_PER_BASE,
    b.BASE_QUANTITY AS BOM_BASE_QTY,
    b.GOLD_UNIT,
    ROUND((d.DAY_YIELD / NULLIF(b.BASE_QUANTITY, 0) * b.COMPONENT_QUANTITY)/1000, 2) AS CALCULATED_GOLD,
    r.BDMNG AS RESB_REQUIREMENT_QTY,
    r.ENMNG AS RESB_WITHDRAWN_QTY
FROM daily_yield d
JOIN MLX_DATALAKE.MLX_SAP_ECC.RESB r
    ON d.AUFNR = r.AUFNR
    AND r.WERKS = '1901'
    AND r.MATNR IN (
        '000000000080950001',
        '000000008000063922',
        '000000000080950004'
    )
LEFT JOIN bom_rate b
    ON r.BAUGR = b.MATERIAL_NUMBER
    AND r.STLNR = b.BILL_OF_MATERIAL_NUMBER
    AND r.STLAL = b.ALTERNATIVE_BOM
    AND r.WERKS = b.PLANT
    AND r.MATNR = b.BOM_COMPONENT
ORDER BY d.AUFNR, d.POSTING_DATE, r.MATNR;