-- Van chuyen GI GR PHYSICALLY VANG 
--   • 261 = gold was issued (consumed) for production 
--   • 531 = gold scrap/by-product was returned
--   • 262/532 = corrections to the above if someone posted in error
-- reminder: check each po through sql not results(not show up)
WITH daily_yield AS (
    SELECT
        AUFNR,
        TO_DATE(BUDAT, 'YYYYMMDD') AS POSTING_DATE,
        SUM(GMNGA) AS DAY_YIELD,
        SUM(XMNGA) AS DAY_SCRAP,
        GMEIN AS YIELD_UNIT
    FROM MLX_DATALAKE.MLX_SAP_ECC.AFRU
    WHERE WERKS = '1901'
        AND VORNR = '0020'
    GROUP BY AUFNR, BUDAT, GMEIN
),
daily_gold AS (
    SELECT
        DOCUMENT_SEGMENT_MATERIAL_ORDER AS ORDER_NUMBER,
        POSTING_DATE,
        SUM(CASE WHEN INVENTORY_MOVEMENT_TYPE_CODE = '261' THEN MATERIAL_MOVEMENT_QUANTITY ELSE 0 END) AS GOLD_ISSUED,
        SUM(CASE WHEN INVENTORY_MOVEMENT_TYPE_CODE = '262' THEN MATERIAL_MOVEMENT_QUANTITY ELSE 0 END) AS GOLD_ISSUED_REVERSAL,
        SUM(CASE WHEN INVENTORY_MOVEMENT_TYPE_CODE = '531' THEN MATERIAL_MOVEMENT_QUANTITY ELSE 0 END) AS GOLD_BYPRODUCT,
        SUM(CASE WHEN INVENTORY_MOVEMENT_TYPE_CODE = '532' THEN MATERIAL_MOVEMENT_QUANTITY ELSE 0 END) AS GOLD_BYPRODUCT_REVERSAL,
        COUNT(*)/2 AS ENTRIES
    FROM MLX_HARMONIZED.MLX_IDSC.MATERIAL_MOVEMENTS
    WHERE PLANT = '1901'
        AND MATERIAL_NUMBER IN (
            '000000000080950001',
            '000000008000063922',
            '000000000080950004')
    GROUP BY DOCUMENT_SEGMENT_MATERIAL_ORDER, POSTING_DATE
)
SELECT
    g.ORDER_NUMBER,
    -- r.BAUGR AS PARENT_MATERIAL,
    -- r.STLNR AS BOM_NUMBER,
    -- r.STLAL AS ALTERNATIVE_BOM,
    g.POSTING_DATE,
    d.DAY_YIELD,
    d.DAY_SCRAP,
    ROUND(g.GOLD_ISSUED, 3) AS GOLD_ISSUED_261,
    ROUND(g.GOLD_ISSUED_REVERSAL, 3) AS GOLD_ISSUED_REVERSAL_262,
    ROUND(g.GOLD_BYPRODUCT, 3) AS GOLD_BYPRODUCT_531,
    ROUND(g.GOLD_BYPRODUCT_REVERSAL, 3) AS GOLD_BYPRODUCT_REVERSAL_532,
    -- ROUND(g.GOLD_ISSUED - g.GOLD_ISSUED_REVERSAL - g.GOLD_BYPRODUCT + g.GOLD_BYPRODUCT_REVERSAL, 3) AS NET_GOLD_CONSUMED,
    g.ENTRIES/2 AS ENTRIES
FROM daily_gold g
JOIN daily_yield d
    ON g.ORDER_NUMBER = d.AUFNR
    AND g.POSTING_DATE = d.POSTING_DATE
-- LEFT JOIN (
--     SELECT DISTINCT AUFNR, BAUGR, STLNR, STLAL
--     FROM MLX_DATALAKE.MLX_SAP_ECC.RESB
--     WHERE WERKS = '1901'
--         AND MATNR IN (
--             '000000000080950001',
--             '000000008000063922',
--             '000000000080950004'
--         )
-- ) r ON g.ORDER_NUMBER = r.AUFNR
--and g.ORDER_NUMBER ='000861805127'
where g.posting_date >= '2026-04-30'
ORDER BY g.ORDER_NUMBER, g.POSTING_DATE
;