-- Van chuyen GI GR PHYSICALLY VANG 
--   • 261 = gold was issued (consumed) for production 
--   • 531 = gold scrap/by-product was returned
--   • 262/532 = corrections to the above if someone posted in error
-- reminder: check each po through sql not results(not show up)
WITH daily_yield AS (
    SELECT
        AUFNR,
        TO_DATE(BUDAT, 'YYYYMMDD') AS POSTING_DATE,
        SUM(GMNGA) AS DAY_YIELD,
        SUM(XMNGA) AS DAY_SCRAP,
        GMEIN AS YIELD_UNIT
    FROM MLX_DATALAKE.MLX_SAP_ECC.AFRU
    WHERE WERKS = '1901'
        AND VORNR = '0020'
    GROUP BY AUFNR, BUDAT, GMEIN
),
daily_gold AS (
    SELECT
        DOCUMENT_SEGMENT_MATERIAL_ORDER AS ORDER_NUMBER,
        POSTING_DATE,
        MATERIAL_NUMBER AS GOLD_CODE,
        INVENTORY_MOVEMENT_TYPE_CODE AS MOVEMENT_TYPE,
        INVENTORY_MOVEMENT_TYPE_DESCRIPTION AS MOVEMENT_DESC,
        SUM(MATERIAL_MOVEMENT_QUANTITY) AS GOLD_QTY,
        COUNT(*) AS ENTRIES
    FROM MLX_HARMONIZED.MLX_IDSC.MATERIAL_MOVEMENTS
    WHERE PLANT = '1901'
        AND MATERIAL_NUMBER IN (
            '000000000080950001',
            '000000008000063922',
            '000000000080950004'
        )
    GROUP BY DOCUMENT_SEGMENT_MATERIAL_ORDER, POSTING_DATE, MATERIAL_NUMBER,
                INVENTORY_MOVEMENT_TYPE_CODE, INVENTORY_MOVEMENT_TYPE_DESCRIPTION
)
SELECT
    g.ORDER_NUMBER,
    r.BAUGR AS PARENT_MATERIAL,
    g.GOLD_CODE,
    g.MOVEMENT_TYPE,
    g.MOVEMENT_DESC,
    r.STLNR AS BOM_NUMBER,
    r.STLAL AS ALTERNATIVE_BOM,
    g.POSTING_DATE,
    d.DAY_YIELD,
    d.DAY_SCRAP,
    ROUND(g.GOLD_QTY, 3) AS GOLD_QTY,
    g.ENTRIES,
    r.BDMNG AS RESB_REQUIREMENT_QTY,
    r.ENMNG AS RESB_WITHDRAWN_QTY
FROM daily_gold g
JOIN daily_yield d
    ON g.ORDER_NUMBER = d.AUFNR
    AND g.POSTING_DATE = d.POSTING_DATE
LEFT JOIN MLX_DATALAKE.MLX_SAP_ECC.RESB r
    ON g.ORDER_NUMBER = r.AUFNR
    AND r.WERKS = '1901'
    AND r.MATNR = g.GOLD_CODE
--WHERE g.ORDER_NUMBER = '000861805127'
;